FROM tomcat:9.0.46-jdk8

RUN apt-get update \
    && apt-get install -y maven \
    && apt-get install -y git \
    && cd ~/ \
    && git clone https://github.com/boomzin/game.git \
    && cd ~/game \
    && mvn -DskipTests=true clean package \
    && cp ~/game/target/rpg-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/rpgadminpanel.war
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8080
EXPOSE 3306
